### ISSUE TITLE
Problems with the development version of tibble

### ISSUE THREAD

**Issue by krlmlr** [jlacko/RCzechia#10]
I'm in the process of preparing the release for _tibble_ 2.0.0. The _RCzechia_ package imports or suggests _tibble_.

I'm seeing errors when testing your package with the dev version of _tibble_. Unfortunately I can't relate the errors I see to changes we've made to _tibble_. Also, a first pass of checking all downstream dependencies did not catch this problem.

Could you please install the development version of _tibble_ and run the tests in your package, so that we get a better understanding for the reason of the new test failures?

See https://www.tidyverse.org/articles/2018/11/tibble-2.0.0-pre-announce/ for details on the upcoming release.

**Comment by jlacko** [comment]
Thanks for raising the issue and doing the check.

The RCzechia package does not depend on `tibble` directly, and it seems that the failure of CMD check was a coincidence - it was most likely caused not by your package, but by the recent release of `readxl` (on 2018-12-19 or so...).

I have amended the vignette, and upon completing further checks will submit version 1.3.2 to CRAN.

Thanks again for taking care!

**Comment by krlmlr** [comment]
Thanks! In my process I'm comparing output of `R CMD check` between stable and development versions of _tibble_, everything else being equal. The process used _readxl_ 1.2.0, and has shown that with the dev version of _tibble_ there are more failures. (I'm not checking if the process failed before, only if there are more failures now.)

Before releasing your package, could you please double-check if all tests pass with both the CRAN and the dev version of _tibble_?

**Comment by jlacko** [comment]
RCzechia version 1.3.2 has passed all checks and was accepted on CRAN.
