### ISSUE TITLE
URL encoding of czech characters in geocode() function

### ISSUE THREAD

**Issue by FHabarta** [jlacko/RCzechia#14]
Hello,

I would suggest different way of URL encoding for geocode() function to deal with special czech characters - recode adress to ASCII.  Current approach seems to fail a lot as URLencode function (and others in R) works differently compared to Chrome/Edge url encoding... See example below.

  Example adress:
  address <- c("Dr. Stejskala 426/15, České Budějovice 1, České Budějovice")
  
  Suggestion:
  cil <- gsub(" ", "+", address) %>% 
    iconv(to = 'ASCII//TRANSLIT') %>% # get rid of funny Czech characters
    utils::URLencode() 
  
  Current approach:
  cil <- gsub(" ", "+", address) %>% # spaces to pluses (for url use)
    utils::URLencode() # get rid of funny Czech characters
  
  Generated URL:
  By chrome (after pasing original adress):
   http://ags.cuzk.cz/arcgis/rest/services/RUIAN/Vyhledavaci_sluzba_nad_daty_RUIAN/MapServer/exts/GeocodeSOE/find?text=Dr.%20Stejskala%20426/15,%20%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice%201,%20%C4%8Cesk%C3%A9%20Bud%C4%9Bjovice&outSR=4326&maxLocations50=&f=pjson
   Suggestion:
   http://ags.cuzk.cz/arcgis/rest/services/RUIAN/Vyhledavaci_sluzba_nad_daty_RUIAN/MapServer/exts/GeocodeSOE/find?text=Dr.+Stejskala+426/15,+Ceske+Budejovice+1,+Ceske+Budejovice&outSR=4326&maxLocations50=&f=pjson
 Current approach:
   http://ags.cuzk.cz/arcgis/rest/services/RUIAN/Vyhledavaci_sluzba_nad_daty_RUIAN/MapServer/exts/GeocodeSOE/find?text=Dr.+Stejskala+426/15,+%C8esk%E9+Bud%ECjovice+1,+%C8esk%E9+Bud%ECjovice&outSR=4326&maxLocations50=&f=pjson
  
Otherwise, thanks for the great package!

**Comment by jlacko** [comment]
Thank you for your kind words and helpful suggestion!

This is an interesting topic: on one hand the "url" never enters a browser - the R session talks straight to ARC GIS server on ČÚZK - but on the other hand you would not be raising this issue if it did not cause you problems.

I will look into it, and include the town of České Budějovice in my unit testing (everybody wants to live there).

**Comment by jlacko** [comment]
I was not able to reproduce the bug - the existing code was passing the new unit test.
On the other hand your proposal does not break the unit tests either, and I am including for a future release.
Thanks again!

**Comment by jlacko** [comment]
the issue had to be descoped form 1.4.6 due to breaking unit tests on windows platform (unix was OK)

**Comment by jlacko** [comment]
@FHabarta could you elaborate a little bit on the need for the `iconv(to = 'ASCII//TRANSLIT')` ?

I had to descope it from 1.4.6 as it was wreaking havoc on Windows and MacOS environments, and the release was under time pressure due to depencency chain ({lwgeom} was going thru a breaking change).
