### ISSUE TITLE
Version v0.1.4 with seperate sp files

### ISSUE THREAD

**Issue by Danica-Cortez** [jlacko/RCzechia#17]
I don't know if it's just me, but v0.1.4 has only a couple of objects (LAU 1-2). I tried subseting the SpatialPolygonsDf to only include NUTS 3 region but I couldn't manage. After going to v1.5.0, files are sf. Would it be possible to have a version with kraje only in sp?

**Comment by jlacko** [comment]
Hi, the v0.1.4 is ancient; I felt that the world has moved on from {sp} to {sf} - I see I was wrong :)

Would something like this work in your use case? If not I will make a new version or a branch
```
library(RCzechia)
library(sp)

ye_olde_regione <- as(kraje(), "Spatial")

class(ye_olde_regione)
[1] "SpatialPolygonsDataFrame"
attr(,"package")
[1] "sp"
```

**Comment by Danica-Cortez** [comment]
Hello,
Thank you for such a quick reply! I just saw a sf to sp transformation on stack exchange but wasn't sure it would work, great to know! This is perfect, děkuji :)

**Comment by jlacko** [comment]
Oki, glad to be of service!
