### ISSUE TITLE
Geomorphological divisions

### ISSUE THREAD

**Issue by ChrisMUC83** [jlacko/RCzechia#50]
Hi,

thank you for this package. It's very easy to handle, I like it.

I would like to ask if there is a possibility to integrate the Geomorphological divisions (see: https://en.wikipedia.org/wiki/Geomorphological_division_of_the_Czech_Republic)? I know that the national parks and forests are already included in the package but this system of divisions is much more broader and applies to the whole country.

**Comment by jlacko** [comment]
Thanks for your kind words! I will look into this.

My original background is social sciences, so my initial focus were the various kinds of admin areas; but the package has found its use in natural sciences as well (more than I originally expected).

A lot will depend on whether I can find an "master" source of the Geomorphological divisions - the Wikipedia article you linked has three different maps - regions, provinces, subregions... Is it just three levels of hierarchy, or are these something different? And if so, is one of the divisions more relevant than others?

**Comment by jlacko** [comment]
There seems to be a reasonably friendly data source available from https://geoportal.gov.cz/ (originally AOPK)  in WMS format that is CC-BY-4.0 licensed (= fair game).

I will digest the data & prepare it for a future `{RCzechia}` release; there is no planned date as yet.

**Comment by jlacko** [comment]
Thank you for the pointer and advice; I was able to get a raw dataset, and will polish it up & prepare the necessary code + documentation for a future release.

A slight inconvenience is that I have a paper on `{RCzechia}` package under review for https://joss.theoj.org/ and I would prefer not to alter the package functionality too much until the review process is finalized, creating confusion.

**Comment by jlacko** [comment]
The geomorfo() function now provides 8 levels of geomorfo detail - from system (n = 2) down to okrsek (n = 933)

Since I was kind of rushed to release - due to sloppiness in releasing 1.11, sorry for that - I will appreciate a test & a thorough shakedown.  Wink wink @ChrisMUC83 ....

**Comment by ChrisMUC83** [comment]
> The geomorfo() function now provides 8 levels of geomorfo detail - from system (n = 2) down to okrsek (n = 933)
> 
> Since I was kind of rushed to release - due to sloppiness in releasing 1.11, sorry for that - I will appreciate a test & a thorough shakedown. Wink wink @ChrisMUC83 ....

@jlacko : I tested the geomorfo-function and everything worked well. Thank you!

**Comment by jlacko** [comment]
Perfect, thank you!
