### ISSUE TITLE
Community guidelines:  JOSS Review

### ISSUE THREAD

**Issue by nickbearman** [jlacko/RCzechia#59]
You do say people can contribute, but I think it would be good to have a CONTRIBUTING.md file, similar to this:

https://github.com/kadyb/rgugik/blob/master/CONTRIBUTING.md

And a Code of Conduct. These integrate with GitHub's issues etc. 

I think it would also be worth mentioning somewhere about adding new data / updating existing data. At the minimum, "If you would like to contribute new data to this library, or notice data that needs updating, please open an issue" or similar. 

https://github.com/openjournals/joss-reviews/issues/5082

**Comment by nickbearman** [comment]
Thanks - I see you have added a link to https://www.contributor-covenant.org/version/2/1/code_of_conduct/ on the README.md page and also added a CODE_OF_CONDUCT.md in the repo. Would it not make more sense to link from README.md to CODE_OF_CONDUCT.md rather than an external site?

**Comment by jlacko** [comment]
I confess to having used a bolierplate code of conduct - `usethis::use_code_of_conduct()` - which is  a function that on one hand enforces a certain level of consistency and "best practices", but on the other hand is just that -a bolierplate.

I will double check it, and in addition write a short contributing guide.

**Comment by jlacko** [comment]
I have updated README to link properly to both the local code of conduct and the newly introduced contributing guidelines; I am closing the issue.

**Comment by nickbearman** [comment]
Wonderful - thanks very much
