### ISSUE TITLE
Install dev version: JOSS Review

### ISSUE THREAD

**Issue by nickbearman** [jlacko/RCzechia#60]
I'm not sure if this is a me problem or a code problem. 

When I try to install the dev version:

`remotes::install_github("jlacko/RCzechia")`

I get this message:

`Downloading GitHub repo jlacko/RCzechia@HEAD`
then it downloads a bit. 
Then: 
`Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/jlacko/RCzechia/tarball/HEAD' failed`

Anyone else have this issue?

https://github.com/openjournals/joss-reviews/issues/5082

**Comment by jlacko** [comment]
I can't tell for 100% certain if this was the cause, but I was doing a merge to main a while back (#54) and the API might have been busy. If this was the problem then it was just an unfortunate coincidence.

**Comment by jlacko** [comment]
In addition to the possible merge issue it seems that the HEAD of the dev version has been unnecessarily big. It contains some backup directories with raw data that are ignored on R package build, but are downloaded via git (and then discarded).
I will move these to a separate branch where they will cause no harm.

**Comment by jlacko** [comment]
I have slimmed the git HEAD to ~ 2.4 MB, and the install of dev version should be way smoother now (I have checked).

Thanks for reporting the issue!

**Comment by nickbearman** [comment]
Thanks - just checked and this works well for me now. :-D
